services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: sistema-reserva-salas-api

    ports:
      - "3001:3001"

    env_file:
      - .env

    restart: unless-stopped